# Generated by Django 2.2.2 on 2019-08-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postname', models.CharField(max_length=200)),
                ('postimage', models.ImageField(upload_to='pics')),
                ('postdesc', models.TextField()),
                ('postcatagoty', models.TextField()),
                ('date', models.IntegerField()),
                ('month', models.CharField(max_length=30)),
            ],
        ),
    ]
