# Generated by Django 2.2.2 on 2019-08-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination_indi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Destination_individual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics_indiavidual')),
                ('caption', models.CharField(max_length=100)),
                ('img2', models.ImageField(upload_to='pics_indiavidual')),
                ('caption2', models.CharField(max_length=100)),
                ('img3', models.ImageField(upload_to='pics_indiavidual')),
                ('caption3', models.CharField(max_length=100)),
                ('img4', models.ImageField(upload_to='pics_indiavidual')),
                ('caption4', models.CharField(max_length=100)),
                ('img5', models.ImageField(upload_to='pics_indiavidual')),
                ('caption5', models.CharField(max_length=100)),
            ],
        ),
    ]
