# Generated by Django 2.2.2 on 2019-08-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_destination_indi_destination_individual'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination_individual',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
