# Generated by Django 2.2.2 on 2019-08-08 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_remove_destination_individual_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination_individual',
            name='name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='my_app.Destination', to_field='name'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
