# Generated by Django 2.2.2 on 2019-08-08 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_auto_20190808_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination_individual',
            name='about_the_city',
            field=models.TextField(default=''),
        ),
    ]
